version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  web:
    build: .
    ports:
      - "3002:3000"
    depends_on:
      - mongo

volumes:
  db: ~
